application:
  name: "Kirebos Networks"
  version: "1.0.0"
  environment: "production"

logging:
  level: "info"
  file: "logs/kirebos_networks.log"

network:
  defaultInterface: "auto"
  firewallEnabled: true
  maxLoginAttempts: 5
