# Advanced DMZ Configuration
firewall_rules:
  - rule: "Allow all outbound connections"
  - rule: "Block all inbound connections"
  - rule: "Allow specific IP ranges for administrative access only"
monitoring:
  log_level: "detailed"
  frequency: "5 seconds" # Interval for monitoring checks
failover:
  enabled: true
  primary_ip: "192.168.1.1"
  secondary_ip: "192.168.1.2"
  switch_time: "30 seconds"
alerts:
  email: "admin@kirebosnetworks.com"
  sms: "+1234567890"
