application:
  name: "Kirebos Networks Flip Phone"
  version: "1.0.0"
  environment: "flip_phone"

settings:
  auto_start: false
  battery_optimization: true
  max_connections: 1  # Limite le nombre de connexions simultanées
