logging:
  level: "info"                      # Niveau de log minimal
  file_path: "logs/flip_phone.log"
  max_file_size: 2MB                 # Limite de taille pour économiser de l'espace
  backup_count: 1                    # Une seule sauvegarde de log
